### PR TITLE
T951: Fixed isolate-stations boolean condition bug

### PR DESCRIPTION
**Pull request by atoy40**

### CODE REVIEW

**Comment by dmbaturin** [comment]
Generally, we should change that node to valueless I think.

**Comment by atoy40** [comment]
@dmbaturin I'm new to vyos contribution, and I haven't really understand branch managment in vyOs :S Will this patch be include in the next LTS release ? or does it has to be merge into the crux branch ? Thanks for info. Anthony.

**Comment by dmbaturin** [comment]
This one is backwards compatible and fixes a bug, so yes, I'll cherry-pick it into the current LTS branch (crux).

**Comment by atoy40** [comment]
@dmbaturin do you know when this cherry-pick to make a new release will be done ? is it at fixed date ?
thanks

**Comment by atoy40** [comment]
@dmbaturin it seems this patch has not been included in the last vyos release (1.3.4). Is it possible to add it to the next 1.2.5 ? (even if there is already a early release)

**Pull request merged**
